name: Close stale issues and PRs

on:
  schedule:
  - cron: '30 1 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-issue-stale: 45
        days-before-pr-stale: 45
        days-before-issue-close: 5
        days-before-pr-close: 5
